### ISSUE TITLE
Project will not run due to 'mongoose'

### ISSUE THREAD

**Issue by AndrewKralovec** [SIU-CS-435/Alpha-Learning#28]
So the branch tim added uses mongoose, but i guess something went wrong ,because mongoose is not in our project. The master i broken. Do not make any pull requests until this is fixed. 

```

node --debug-brk=21626 --nolazy bin/www 
Debugger listening on port 21626
module.js:338
    throw err;
          ^
Error: Cannot find module 'mongoose'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/andrew/Git/AlphaLearning/app.js:7:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by AndrewKralovec** [comment]
Well i see  mongoose in your package.json.

**Comment by AndrewKralovec** [comment]
Debugger listening on port 12584
/home/andrew/Git/AlphaLearning/node_modules/connect-mongo/src/index.js:3
const Promise = require('bluebird');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/andrew/Git/AlphaLearning/node_modules/connect-mongo/index.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/andrew/Git/AlphaLearning/routes/login.js:18:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/andrew/Git/AlphaLearning/app.js:12:13)

**Comment by AndrewKralovec** [comment]
Tim How is your project running?

**Comment by AndrewKralovec** [comment]
I'm not the only one getting this right?
I got an old branch i can push to the master, so we can have a working master branch until we figure this out.

**Comment by TimLunik** [comment]
Pretty sure that error has something to do with connect- mongo, but I couldn't figure out what it was so I just commented it out. My bad, should have told you.

**Comment by TimLunik** [comment]
Something about an es5 version of connect-mongo might work.

**Comment by AndrewKralovec** [comment]
No, i commented out all your code, still same error. Im removing the new master

**Comment by AndrewKralovec** [comment]
Does anyone have a copy of the old branch. I can't test out any of my new code, with this error

**Comment by AndrewKralovec** [comment]
Removed Modules, commented out code and it  fixed bug
